config/routes.rb
P2ex::Application.routes.draw do
  devise_for :users

  resources :topics

  resources :spaces

  root :to => 'home#index'

end

app/models/space.rb
class Space < ActiveRecord::Base
  attr_accessible :display_name, :name
  has_many :topics
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :content, :title, :user_id, :space_id
  belongs_to :space
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@spaces = Space.all
	end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  # GET /spaces
  # GET /spaces.json
  def index
    @spaces = Space.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @spaces }
    end
  end

  # GET /spaces/1
  # GET /spaces/1.json
  def show
    @space = Space.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @space }
    end
  end

  # GET /spaces/new
  # GET /spaces/new.json
  def new
    @space = Space.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @space }
    end
  end

  # GET /spaces/1/edit
  def edit
    @space = Space.find(params[:id])
  end

  # POST /spaces
  # POST /spaces.json
  def create
    @space = Space.new(params[:space])

    respond_to do |format|
      if @space.save
        format.html { redirect_to @space, notice: 'Space was successfully created.' }
        format.json { render json: @space, status: :created, location: @space }
      else
        format.html { render action: "new" }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /spaces/1
  # PUT /spaces/1.json
  def update
    @space = Space.find(params[:id])

    respond_to do |format|
      if @space.update_attributes(params[:space])
        format.html { redirect_to @space, notice: 'Space was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spaces/1
  # DELETE /spaces/1.json
  def destroy
    @space = Space.find(params[:id])
    @space.destroy

    respond_to do |format|
      format.html { redirect_to spaces_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new
    @space = Space.find(params[:space_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic.space, notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/home/index.html.erb
<% @spaces.each do |space| %>
<div class="row home mb20">
	<div class="span3"></div>
	<div class="span6 node-block">
		<div class="title pull-left"><%= link_to space.name, space %></div>
		<div class="brief pull-left">工头：<%=link_to 'Fistan', nil, :class => "mr10" %>创建于：2012/10/03</div>
	</div>
	<div class="span3"></div>
</div>
<% end %>

<div class="row home">
	<div class="span3"></div>
	<div class="span6 node-block-next">
		What's next ? <%= link_to 'Apply' %>
	</div>
	<div class="span3"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>P2ex</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<h1 style="text-align:center;">- <%= link_to 'P2EX', root_path %> -</h1>
	<p class="login mb20">
		<% if signed_in? %>
		<%= current_user.email %>, <%= link_to "退出", destroy_user_session_path, :method => :delete %>
	  <% else %>
		<%= link_to '登录', new_user_session_path %> / <%= link_to '注册', new_user_registration_path %>
		<% end %>
	</p>
	
	<%= yield %>

	<div class="footer">Yan's - 2012/10/19</div>
</div>

</body>
</html>

app/views/spaces/_form.html.erb
<%= form_for(@space) do |f| %>
  <% if @space.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@space.errors.count, "error") %> prohibited this space from being saved:</h2>

      <ul>
      <% @space.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :display_name %><br />
    <%= f.text_field :display_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spaces/edit.html.erb
<h1>Editing space</h1>

<%= render 'form' %>

<%= link_to 'Show', @space %> |
<%= link_to 'Back', spaces_path %>

app/views/spaces/index.html.erb
<h1>Listing spaces</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Display name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @spaces.each do |space| %>
  <tr>
    <td><%= space.name %></td>
    <td><%= space.display_name %></td>
    <td><%= link_to 'Show', space %></td>
    <td><%= link_to 'Edit', edit_space_path(space) %></td>
    <td><%= link_to 'Destroy', space, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Space', new_space_path %>

app/views/spaces/new.html.erb
<h1>New space</h1>

<%= render 'form' %>

<%= link_to 'Back', spaces_path %>

app/views/spaces/show.html.erb
<div class="row">
	<div class="span8 space_content">
		
		<div class="space_info_header mb10">
			<div class="inner">
				<h2><%= @space.display_name %></h2>
			</div>
		</div>
		
		<p id="notice"><%= notice %></p>
		
		<div class="topics">
			<% @topics = @space.topics %>
			<% @topics.each do |t| %>
				<div class="topic mb2">
					<div class="title">
						<%= link_to t.title, t %>
					</div>
					<div class="lighter"><small>茉莉 / Fistan</small></div>
				</div>
			<% end -%>
		</div>

	</div>
	<div class="span4 space_sidebar">
		<div class="inner">
			<%= link_to '+ Topic', new_topic_path(:space_id => @space.id) %>
		</div>
	</div>
</div>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :class => 'input-xlarge' %>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content, :rows => 10, :class => 'input-xxlarge' %>
  </div>
  <%= f.hidden_field :space_id, :value => params[:space_id] %>
  <div class="actions">
    <%= f.submit %> <%= link_to 'Cancel', @topic %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

app/views/topics/index.html.erb
<h1>Listing topics</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @topics.each do |topic| %>
  <tr>
    <td><%= topic.title %></td>
    <td><%= topic.content %></td>
    <td><%= topic.user_id %></td>
    <td><%= link_to 'Show', topic %></td>
    <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
    <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h2>New topic</h2>

<%= render 'form' %>

<%= link_to 'Back', space_path(@space) %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
	<div class="topic_content span7">
		<div class="inner">
			<p><%= link_to "← #{@topic.space.display_name}, 返回列表", @topic.space %></p>
			<h2><%= @topic.title %></h2>
			<p class="mt5 lighter"><small>更新 (12)：<%= @topic.updated_at.strftime("%Y-%m-%d %H:%M:%S") %> / 发表：<%= @topic.created_at.strftime("%Y-%m-%d %H:%M:%S") %> <%= link_to 'Edit', edit_topic_path(@topic, :space_id => @topic.space.id) %></small></p>
			<hr />
			<div><%= simple_format(@topic.content) %></div>
		</div>
	</div>

	<div class="topic_replies span5">
		
		<div class="topic_replies_form clearfix">
			<%= text_area_tag :reply, nil, :rows => 3, :class => 'input-fullsize' %>
			<%= link_to "回复", nil, :class => 'pull-right btn btn-mini' %>
		</div>

		<div class="list"></div>

	</div>
</div>